apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curler
  name: curler
spec:
  serviceAccountName: curler
  containers:
  - image: nginx
    name: curler
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: curler
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  verbs:
  - watch
  - get
  - list
- apiGroups:
    - pepr.dev
  resources:
    - peprstores
  verbs:
    - create
    - get
    - patch
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: curler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: curler
subjects:
- kind: ServiceAccount
  name: curler
  namespace: default
