name: Version Releaes

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: "Zarf Agent: Login to GHCR"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ github.token }}

      - name: Publish to GHCR & NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          #!/bin/bash

          npm ci
          npm --no-git-tag-version version ${{ github.ref_name }}
          npm build

          docker buildx build --push --platform linux/arm64/v8,linux/amd64 --build-arg VER=${{ github.ref_name }} --tag ghcr.io/defenseunicorns/pepr/controller:${{ github.ref_name }} .

          PEPR_VERSION=${{ github.ref_name }} npm publish
