name: Version Releaes

on:
  push:
    tags:
      - 0.*

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.base_ref, 'main')

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - run: npm ci
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
