name: Version Releaes

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - run: npm ci

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          #!/bin/bash

          LOCAL_VER=$(npm pkg get version)
          PUB_VER=$(npm view pepr version)

          echo "Checking if pepr@${LOCAL_VER} exists in the npm registry..."

          if [[ ${LOCAL_VER} == ${PUB_VER} ]]; then
            echo "pepr@${LOCAL_VER} already exists in the npm registry."
          else
            echo "pepr@${LOCAL_VER} does not exist in the npm registry."
            echo "Publishing the package..."
            npm publish
          fi
