name: Version Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: "Zarf Agent: Login to GHCR"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ github.token }}

      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm whoami
          npm ci
          npx semantic-release

      - name: Publish to GHCR
        run: |
          echo "Publishing the image..."
          source .env
          docker buildx build --push --platform linux/arm64/v8,linux/amd64 --build-arg VER=$NEW_VERSION --tag ghcr.io/defenseunicorns/pepr/controller:$NEW_VERSION .
