name: Version Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      NEW_VERSION: ${{ steps.semantic.outputs.new_version }}

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: "Zarf Agent: Login to GHCR"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ github.token }}

      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release

      - name: Publish to GHCR
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing the image..."
          docker buildx build --push --platform linux/arm64/v8,linux/amd64 --build-arg VER=${{ env.NEW_VERSION }} --tag ghcr.io/defenseunicorns/pepr/controller:${{ env.NEW_VERSION }} .
